apiVersion: v1
kind: Service
metadata:
  name: autodealer
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: autodealer
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: usercore
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: usercore
  ports:
    - port: 80
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: apigateway
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
