services:
  redis:
    image: redis
    ports:
      - "6379:6379"
        
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    networks:
      - kafka
  
  autodealer:
    image: autodealer
    build:
      context: .
      dockerfile: Autodealer/Dockerfile

  usercore:
    image: usercore
    build:
      context: .
      dockerfile: UserCore/Dockerfile
      
networks:
  kafka: