services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  autodealer:
    image: autodealer
    build:
      context: .
      dockerfile: Autodealer/Dockerfile

  usercore:
    image: usercore
    build:
      context: .
      dockerfile: UserCore/Dockerfile

  usercore-1:
    image: usercore-1
    build:
      context: .
      dockerfile: UserCore/Dockerfile
