global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'apigateway'
    static_configs:
      - targets: ['apigateway:8080']
    metrics_path: /metrics

  - job_name: 'autodealer'
    static_configs:
      - targets: ['autodealer:8081']
    metrics_path: /metrics
    
  - job_name: 'usercore'
    static_configs:
      - targets: [ 'usercore:8082' ]
    metrics_path: /metrics