apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    jsonData:
      httpMode: GET
      maxTagChars: 256
      maxTraceAge: "168h"
      timeout: 30s
